<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'comment'				=> "Комментарий",
'posted_by'				=> "Автор:",
'entry'				=> "Запись",
'readentry'				=> "Читать запись",
'last_entry_in'				=> "в",
'visit_blog'				=> "Посетить этот блог",
'noblogentries'				=> "Нет записей в блогах",
'latest_entries_title'				=> "Последние записи в блогах",
'search_posted_by'				=> "от",
'search_posted_on'				=> "-",
'search_posted_in'				=> "Добавлено в",
'blogger_error_1'				=> "Нет прав на удаление записи",
'blogger_error_2'				=> "Запись с id (%s) не найдена",
'blogger_deleted_log'				=> "Удалил(а) запись в блоге",
'blogger_blog_prefix'				=> "Блог",
'blogger_error_3'				=> "Неизвестный ID блога",
'blogger_error_4'				=> "Запись с id (%s) не найдена",
'blogger_banned_msg'				=> "Вы заблокированы",
'blogger_unknown_user'				=> "Неизвестный пользователь",
'blogger_suspended'				=> "Пользователь (временно) заблокирован",
'blogger_board_offline'				=> "Сайт отключен",
'blogger_noxmlrpc'				=> "Интерфейс отключен",
'blogger_nopost'				=> "Нет разрешения писать в блогах",
'blogger_inv_pass'				=> "Неправильный пароль",
'blogger_emptypost'				=> "Очистил(а) сообщение",
'blogger_noblog'				=> "Блоги этого пользователя не найдены",
'blogger_toolong'				=> "Сообщение слишком длинное",
'blogger_notitle'				=> "Не указано название записи",
'blogger_title_toolong'				=> "Слишком длинное название записи",
'blogger_error_5'				=> "Этот действие не поддерживается!",
 ); 
