<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'blog_loc_list'				=> "Смотрит блоги",
'blog_loc_ucp'				=> "В панели управления",
'blog_loc_post'				=> "Добавляет запись или комментарий",
'blog_loc_attach'				=> "Смотрит присоединенный файл блога",
'blog_loc_show'				=> "Смотрит блоги",
'blog_loc_entry'				=> "Смотрит запись в блоге",
'blog_loc_blog'				=> "Смотрит блог",
 ); 
