<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'subject__new_comment_on_entry'				=> "Новый комментарий к",
'footer'				=> "С наилучшими пожеланиями,

Команда <#BOARD_NAME#>.
<#BOARD_ADDRESS#>",
'new_comment_on_entry'				=> "Здравствуйте!

Это сообщение было отправлено с: <#BOARD_NAME#>.

Новый комментарий был оставлен в <#BLOG_NAME#>.

----------------------------------
Запись: <#ENTRY_NAME#>
Автор: <#POSTER#>
Комментарий:
<#COMMENT#>
----------------------------------

Комментарий находится здесь:
<#URL#>",
'subject__subs_new_entry'				=> "Уведомление о новой записи в блоге",
'send_entry_text'				=> "Я думаю, тебе будет интересно почитать этот блог: <#THE LINK#>

От,

<#USER NAME#>",
'subs_new_entry'				=> "<#NAME#>,

<#POSTER#> только что разместил новую запись \"<#ENTRY_NAME#>\" в блоге \"<#BLOG_NAME#>\".

----------------------------------------------------------------------
<#ENTRY#>
----------------------------------------------------------------------

Ссылка на запись:
<#BOARD_ADDRESS#>?app=blog&module=display&section=blog&blogid=<#BLOG_ID#>&showentry=<#ENTRY_ID#>

Отменить подписку:
--------------

Вы можете отменить подписку в любой момент из своей панели управления, нажав ссылку \"Трекер блогов\" во вкладке \"Блоги\".",
'header'				=> "",
 ); 
