<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'perm_calendar_start'				=> "Create Events",
'perm_calendar_nomod'				=> "Bypass Moderation",
'perm_calendar_view'				=> "Show Calendar",
'c_singleday'				=> "Single Day Event On:",
'c_tocolon'				=> "To:",
'c_ranged'				=> "Ranged Event",
'c_fromcolon'				=> "From:",
'c_recurring'				=> "Recurrent Event",
'c_completeform'				=> "You must complete the entire form.",
'c_removed'				=> "Calendar Removed",
'c_noid'				=> "No ID was passed. Please try again.",
'c_recachecal'				=> "Recache Calendar Events",
'c_savebutton'				=> "Save Changes",
'c_editbutton'				=> "Edit Calendar ",
'c_edited'				=> "Calendar Edited",
'c_added'				=> "New Calendar Added",
'c_title'				=> "Calendar Manager",
'c_rssrecached'				=> "Calendar Events RSS Recached",
'c_recached'				=> "Calendar Events Recached",
'c_block_mod'				=> "<strong>Calendar: Enable Moderation</strong>",
'c_block_title'				=> "<strong>Calendar: Title</strong>",
'c_block_mod_info'				=> "If enabled, all groups which are not included in the 'Avoid Moderation Queue' will have their events entered into the moderation queue for approval.",
'c_block_limit'				=> "<strong>Calendar: Event Limit</strong>",
'c_block_bday'				=> "<strong>Calendar: Birthday Limit</strong>",
'c_block_limit_info'				=> "This is the number of events listed per day before they are replaced by a single link to the day's events",
'c_block_rss'				=> "<strong>RSS Options</strong>",
'c_block_bday_info'				=> "This is the number of birthdays listed per day before they are replaced by a single link<br />Enter 0 to not show birthdays at all",
'c_block_enable'				=> "<strong>RSS: Enable</strong>",
'c_block_enable_info'				=> "If enabled, all <em>n</em> forthcoming events (based on GMT time) that have guest read permission will be exported",
'c_block_forthcoming'				=> "<strong>RSS: Forthcoming Days</strong>",
'c_block_max'				=> "<strong>RSS: Export Maximum Events</strong>",
'c_block_max_info'				=> "The maximum number of events exported",
'c_block_freq'				=> "<strong>RSS: Update Frequency</strong>",
'c_block_freq_info'				=> "The number of minutes between RSS cache rebuilding",
'c_options'				=> "Options",
'c_calendars'				=> "Calendars",
'c_editcal'				=> "Edit Calendar...",
'c_rebuildcal'				=> "Rebuild Calendar RSS Export...",
'c_addcal'				=> "Add New Calendar",
'c_deletecal'				=> "Delete Calendar...",
 ); 
