<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'sigmachat_help_text'				=> "Выберите вариант",
'sigmachat_chatsigma'				=> "1",
'sigmachat_help'				=> "Live Chat Help",
'sigmachat_online'				=> "Chatting in live chat",
'chat_online'				=> "Chatting in live chat",
 ); 
