<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'ls_members'				=> "Members",
'livesearchmemid'				=> "ID: ",
'ls_acppages'				=> "ACP Pages",
'ls_help'				=> "Help Files",
'ls_settings'				=> "Settings",
'ls_quick_search'				=> "Quick Search",
'ls_view_more_acp'				=> "View more ACP Pages",
'ls_view_more_help'				=> "View more help files",
'ls_view_more_settings'				=> "View more settings",
'ls_groups'				=> "Groups Form",
'ls_forums'				=> "Forums",
'ls_view_more_forums'				=> "View more forums",
'ls_groupresults'				=> "There are per-group settings that matched your search term &raquo;",
'ls_view_more_groups'				=> "View more groups",
'ls_view_more_mem'				=> "View more members",
'ls_grouptitles'				=> "Groups",
'lsnoresults'				=> "No results",
 ); 
