<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'report_emailpm'				=> "<#MOD_NAME#>,

Это сообщение было отправлено Вам от <#USERNAME#> через ссылку \"Пожаловаться модератору\"

------------------------------------------------

Публикация с жалобой: <#LINK#> 
Ссылка на жалобу: <#REPORTLINK#>

------------------------------------------------
Жалоба:

<#REPORT#>

------------------------------------------------",
'subject_report'				=> "<a href='%s'>%s</a> прислал(а) <a href='%s'>жалобу</a> на <a href='%s'>что-то</a>",
'report_msg_msg'				=> "<strong>Введите текст Вашей жалобы</strong><br /><br />",
'report_msg_page'				=> "Пожаловаться на это сообщение модератору",
'report_msg_title'				=> "Заголовок личного сообщения",
'report_file_msg'				=> "<strong>Введите текст Вашей жалобы</strong><br /><br />",
'report_file_page'				=> "Пожаловаться на этот файл модератору",
'report_file_title'				=> "Имя файла",
'report_gallery_comment_suffix'				=> "- Комментарий",
'report_gallery_image_suffix'				=> "- Изображение",
'report_section_title_site_gallery'				=> "Галерея сайта",
'report_settings_options'				=> "Уведомления",
'report_settings_save'				=> "Сохранить",
'report_settings_by_alert'				=> "<b>Уведомление сайтом?</b><br />При получении жалобы, получать уведомление через сообщение сайта. Вы увидите это сообщение во время просмотра сайта, и Вам не придется заполнять личный почтовый ящик.",
'report_settings_by_email'				=> "Уведомление по e-mail?",
'report_settings_pm_desc'				=> "Получать уведомления о новых жалобах с помощью личных сообщений.",
'reports_no_plugin'				=> "Модуль центра жалоб для указанной Вами публикации настроен неправильно.",
'reports_no_comment_text'				=> "Вы не ввели комментарий для сохранения.",
'no_permission_addreport'				=> "Вы не можете добавлять сами с себя в личные переписки.",
'reported_content_summary'				=> "Публикации с жалобами со всего сайта",
'go_to_section'				=> "Перейти к разделу",
'view_report'				=> "Смотреть сообщение",
'select_all_reports'				=> "Выбрать все жалобы",
'report_by'				=> "Кем:",
'report_updated'				=> "Изменено:",
'no_reports'				=> "Нет жалоб",
'view_member'				=> "Смотреть пользователя",
'configure_notifications'				=> "Настроить уведомления",
'delete_report'				=> "Удалить жалобу",
'report_view_reported'				=> "Смотреть публикацию с жалобой",
'report_join_pm'				=> "Участвовать в личной переписке",
'report_about_pm'				=> "личное сообщение с темой",
'report_about_intro'				=> "Жалоба на",
'reports_h2'				=> "Жалобы",
'mark_status_as'				=> "Пометить как",
'change_status_title'				=> "Изменить статус",
'change_current_status'				=> "Изменить текущий статус",
'current_status'				=> "Текущий статус:",
'comments_h2'				=> "Комментарии",
'posted_prefix'				=> "Автор",
'no_comments_on_report'				=> "К этой жалобе пока нет комментариев.",
'post_button'				=> "Отправить",
'add_comment_title'				=> "Добавить комментарий",
'view_content'				=> "Смотреть публикацию",
'reporting_title'				=> "Жалоба:",
'status'				=> "Статус",
'with_selected'				=> "отмеченные",
'reports_messenger'				=> "Сообщения",
'reports_rss_desc'				=> "Показывает новые жалобы из центра жалоб.",
'report_section_title_site_downloads'				=> "Менеджер файлов",
'report_section_title_msg'				=> "Личное сообщение",
'report_section_title_mem'				=> "Профиль пользователя",
'report_mem_title'				=> "Имя пользователя",
'report_mem_page'				=> "Пожаловаться на этот профиль модератору",
'report_mem_msg'				=> "<b>Введите текст Вашей жалобы</b>",
'report_section_title_cal'				=> "Событие календаря",
'report_cal_title'				=> "Название события",
'report_cal_page'				=> "Пожаловаться на это событие модератору",
'rss_feed_title'				=> "Уведомление о жалобах",
'report_actions'				=> "Настройки жалобы",
'report_cal_msg'				=> "<b>Введите текст Вашей жалобы</b>",
'report_prune_message_done'				=> "Очистка жалоб...",
'report_actions_mark_optgroup'				=> "Пометить жалобу, как",
'older_than'				=> "старше, чем",
'report_prune_message_none'				=> "Нечего чистить...",
'report_prune_days_box'				=> "дней",
'main_title'				=> "Центр жалоб",
'list_title'				=> "Жалобы",
'list_header_title'				=> "Название",
'list_header_section'				=> "Раздел",
'list_header_updated_by'				=> "Кем изменено",
'list_header_last_updated'				=> "Последнее изменение",
'report_basic_url_title'				=> "Жалоба на страницу",
'list_header_comments'				=> "Комментарии",
'list_header_reports'				=> "Жалобы",
'report_basic_enter'				=> "<b>Введите текст Вашей жалобы</b>",
'report_basic_title'				=> "Пожаловаться на эту страницу модератору",
'report_basic_desc'				=> "Обратите внимание: Модератор получит ссылку на эту страницу. <br />Эта форма предназначена ТОЛЬКО для сообщений о нарушениях, и не для общения с модераторами по другим причинам.",
'report_post_url_title'				=> "Название темы",
'report_post_title'				=> "Пожаловаться на это сообщение модератору",
'report_option_delete'				=> "Удалить жалобы",
'report_page_title_unknown'				=> "Название неизвестно",
'report_sending'				=> "Отправка жалобы...",
'report_basic_submit'				=> "Отправить жалобу",
'report_post_enter'				=> "<strong>Введите текст Вашей жалобы</strong>",
'report_option_prune'				=> "Очистить жалобы",
'redirect_mark_status'				=> "Пометка жалоб...",
'active_users_detail'				=> "<strong>%s</strong> пользователей, <strong>%s</strong> гостей, <strong>%s</strong> анонимных пользователей",
'active_users_title'				=> "%s посетителей",
'redirect_delete_report'				=> "Удаление жалоб...",
'report_ajax_tab_notif_meth'				=> "Способы уведомления",
'active_users_members'				=> "%s пользователей:",
'report_comment_saved'				=> "Ваш комментарий успешно сохранен",
'report_settings_by_pm'				=> "Уведомление с помощью личных сообщений?",
'reports_methods_saved'				=> "Ваши настройки уведомлений были сохранены",
 ); 
