<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'enter_username'				=> "Username",
'enter_useremail'				=> "Email Address",
'enter_name_and_email'				=> "Username or Email Address",
'ipb_login'				=> "Invision Power Board: Log in",
'logout_complete'				=> "Log out complete",
'login_successful'				=> "Log in successful",
'no_acp_access'				=> "You do not have permission to access the ACP",
'bad_email_password'				=> "Your login credentials were not valid",
 ); 
