<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'choose_file'				=> "Выберите раздел",
'topic_text'				=> "Вот раздел, который Вы хотели посмотреть",
'help_topics'				=> "Разделы помощи",
'help_txt'				=> "Выберите раздел из списка или воспользуйтесь поиском",
'help_return_list'				=> "Вернуться к списку разделов",
'help_back_list_title'				=> "Назад к списку",
'help_read_document'				=> "Читать документ",
'page_title'				=> "Просмотр разделов помощи",
'help_topic'				=> "Раздел помощи",
'no_help_topics'				=> "There are no help topics yet",
 ); 
