<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'comment_notice_subject'				=> "Новый комментарий к <a href='%s'>%s</a>",
'comment_notifications'				=> "<#NAME#>,

<#AUTHOR#> только что оставил(а) комментарий к \"<#TITLE#>\".

<#COMMENT#>

Вы можете посмотреть новый комментарий здесь:
<#URL#>",
'comment_save'				=> "Сохранить",
'edit_comment'				=> "Редактирование комментария из:",
'delete_comment'				=> "Удалить комментарий",
'delete_link'				=> "Удалить",
'edit_link'				=> "Редактировать",
'comments_header'				=> "Комментарии",
'ignored_comments_not'				=> "Этот комментарий скрыт, потому что Вы предпочли игнорировать сообщения от",
'view_comment'				=> "Смотреть комментарий",
'view_it_anyway'				=> "Посмотреть все равно?",
'permalink'				=> "Постоянная ссылка:",
'comment_reply'				=> "Ответить",
'mq_image_add'				=> "Цитировать",
'report_link'				=> "Жалоба",
'check_all'				=> "Выбрать все",
'comment_button_post'				=> "Добавить комментарий",
 ); 
