<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'freq_daily'				=> "Ежедневно",
'freq_weekly'				=> "Еженедельно",
'freq_offline'				=> "Только когда не на сайте",
'freq_immediate'				=> "Сразу",
'label_anon'				=> "Нравится анонимно",
'label_anon_desc'				=> "Не показывать меня в сводке тех, кому нравится",
'label_freq'				=> "Частота",
'fave_title'				=> "Нравится",
'label_notify'				=> "Получать уведомления о %s",
 ); 
