<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'back_topic'				=> "Вернуться к теме",
'o_word_desc'				=> "Позволит скачать эту тему в формате, доступном для редактирования в Microsoft Word. Будет открыт диалог сохранения файла",
'o_word_title'				=> "Скачать версию для Microsoft Word",
'view_original'				=> "(Смотреть оригинальную тему)",
'please_choose'				=> "Пожалуйста, выберите вариант ниже",
'posted_prefix'				=> "Отправлено",
'end'				=> "конец",
'click_toview'				=> "Нажмите для просмотра темы",
'powered_by'				=> "Работает на",
'forum'				=> "Форум",
'on	'				=> "-",
'title'				=> "Версия для печати",
'start'				=> "автор:",
'by'				=> "Автор:",
'topic'				=> "Тема",
'tvo_title'				=> "Настройки просмотра темы для:",
'o_print_title'				=> "Версия для печати",
'o_print_desc'				=> "Отобразит тему на этой странице в простом формате, удобном для принтера, ничего скачивать не нужно.",
'o_html_title'				=> "Скачать HTML версию",
'o_html_desc'				=> "Позволит скачать эту тему в формате HTML на Ваш жесткий диск. Будет открыт диалог сохранения файла",
 ); 
