<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'bbc_before'				=> "Вы вводите",
'bbc_intro'				=> "BB Code - это быстрый и легкий способ добавлять эффекты или форматирование в Ваши сообщения.<br />Он использует формат, похожий на теги HTML, с которыми Вы, возможно, уже знакомы.<br />Ниже - небольшая инструкция по использованию самых популярных BB Code.",
'emo_title'				=> "Смайлики",
'bbc_after'				=> "Результат",
'bbc_title'				=> "BB Code",
 ); 
