<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'topic_noperms'				=> "У Вас нет прав на доступ к этому форуму",
'topic_noattach'				=> "В данной теме нет присоединенных файлов",
'notopic_attach'				=> "Не удалось загрузить присоединенные файлы для запрошенной темы",
'leader_all_forums'				=> "Все форумы",
'stats_missing_tid'				=> "Для этого Вам нужно выбрать правильную тему",
'leader_forums'				=> "Форумы",
'go_button'				=> "Перейти",
'who_farted'				=> "Кто писал в:",
'who_replied_title'				=> "Кто писал в этой теме",
'no_forums'				=> "Смотреть форумы (всего %s...)",
'goto_profile'				=> "Перейти к профилю",
'whoposted_posts'				=> "Сообщений",
'whoposted_name'				=> "Имя пользователя",
'todays_posters'				=> "Топ 20 авторов сегодня",
'member_posts'				=> "Всего сообщений",
'member'				=> "Пользователь",
'member_joined'				=> "Регистрация",
'member_today'				=> "Сообщений сегодня",
'member_percent'				=> "% сообщений сегодня",
'no_info'				=> "В настоящее время информация недоступна",
'top_poster_title'				=> "Топ 20 авторов сегодня",
'forum_leaders'				=> "Команда модераторов",
'leader_admins'				=> "Администраторы",
'leader_name'				=> "Имя пользователя",
'leader_mods'				=> "Модераторы форума",
'leader_global'				=> "Глобальные модераторы",
'leader_location'				=> "Где сейчас",
 ); 
