<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'strong_avatar_label'				=> "Avatar",
'memchangeavatar'				=> "Change Avatar",
'mem_remove_avatar'				=> "Remove Avatar",
'mem_posts'				=> "Posts",
'mem_change_button'				=> "Change...",
'm_overrride'				=> "Override group permission masks with...",
 ); 
