<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'gallery_loci_idx'				=> "Смотрит главную страницу галереи",
'gallery_loci_sc'				=> "Смотрит категорию: <#CAT#>",
'gallery_loci_si'				=> "Смотрит изображение: <#IMG#>",
'gallery_loci_album'				=> "Смотрит альбом: <#ALBUM#>",
'gallery_loci_sc_na'				=> "Смотрит категорию...",
'gallery_loci_si_na'				=> "Смотрит изображение...",
'gallery_loci_album_na'				=> "Смотрит альбом...",
 ); 
