<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'kicked_pre'				=> "Kicked user ",
'private_pre'				=> "[PRIVATE CHAT with %s] ",
'chat_logs_sub'				=> "View Archived Chat Logs",
'chat_logs'				=> "Chat Logs",
'chat_log_user'				=> "User",
'chat_log_date'				=> "Date",
'chat_logs_none'				=> "There were no logs found.  Try clicking the &quot;Refresh&quot; button to update your local archives.",
'chat_logs_refresh'				=> "Refresh Logs",
'chat_log_message'				=> "Message",
'chat_log__filter'				=> "Search for keyword",
'chat_log__submit'				=> "Update",
'chatlogto'				=> " to ",
'chat_log__daterange'				=> " from ",
'chat_log__publicvis'				=> "Public",
'chat_log__privatevis'				=> "Private",
'chat_log__bothvis'				=> "Both",
'chat_log__publicvisd'				=> "View only publicly posted chat messages",
'chat_log__privatevisd'				=> "View only messages posted in private chats",
'chatlog__hasentered'				=> "%s has entered the room",
'chat_log__bothvisd'				=> "View both publicly and privately posted chat messages",
'chatlog__hasleft'				=> "%s has left the room",
'chatlogs_refreshed'				=> "The chat logs have been refreshed",
'no_chat_account_number'				=> "You have not yet filled in your chat account number",
'mem_form_chat_settings'				=> "Chat Settings",
'ordered_ipchat'				=> "Supply your license key to unlock IP.Chat ",
'btn_continue'				=> "Continue...",
'enter_siteid'				=> "Enter license key here...",
'chat_invalid_key'				=> "You have entered an invalid account key",
'mem_tab_chat'				=> "Chat",
'mem_form_ban_chat'				=> "Ban user from chat",
'chat_title'				=> "IP.Chat",
 ); 
