<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'sort_by'				=> "Сортировать по:",
'mlist_view_all_title'				=> "Смотреть всех пользователей",
'mlist_view_all_txt'				=> "ВСЕ",
'mlist_view_start_title'				=> "Показать пользователей, начинающихся на",
'mlist_header'				=> "Список пользователей",
'mlist_adv_filt'				=> "Расширенный фильтр",
'mlist_adv_filt_opt'				=> "Настройки расширенного фильтра",
'show_all'				=> "Показать все",
'sort_submit'				=> "Применить фильтры",
'sort_by_joined'				=> "По дате регистрации",
'page_title'				=> "Список пользователей",
'sort_by_posts'				=> "По количеству сообщений",
'sort_by_mname'				=> "Сортировать по имени пользователя",
'sorty_by_jdate'				=> "Сортировать по дате регистрации",
'pcount'				=> "По количеству сообщений",
'reputation'				=> "Репутация",
'm_rating'				=> "Оценка",
'm_dd_views'				=> "По просмотрам профиля",
'members_start_with'				=> "Показать пользователей, начинающихся на",
'm_rating_morethan'				=> "Оценка выше, чем",
's_lastpost'				=> "Последнее сообщение",
's_joined'				=> "Дата регистрации",
's_posts'				=> "Количество сообщений",
'm_views'				=> "Просмотров",
'm_stars'				=> "звезд",
's_lastvisit'				=> "Последний вход",
'photo_only'				=> "С фотографией",
's_name'				=> "По имени пользователя",
's_signature'				=> "Подпись содержит",
's_dateformat'				=> "(ММ-ДД-ГГГГ)",
's_contains'				=> "содержит",
's_begins'				=> "начинается с",
's_lessthan'				=> "меньше",
's_morethan'				=> "больше",
's_before'				=> "до",
's_after'				=> "после",
'sorting_text_by'				=> "по",
'member_joined'				=> "Регистрация",
'sort_by_name'				=> "По имени пользователя",
'member_group'				=> "Группа",
'no_results'				=> "Результатов нет",
'member_name'				=> "Имя",
'sorting_text_results'				=> "результатов на странице",
'sorting_text_with'				=> "по",
'sorting_text_in'				=> "в",
'member_posts'				=> "Сообщений",
'descending_order'				=> "В порядке убывания",
'ascending_order'				=> "В порядке возрастания",
 ); 
