<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'WHERE_reports'				=> "Смотрит жалобы",
'WHERE_stats'				=> "Смотрит статистику",
'WHERE_profile'				=> "Смотрит профиль:",
'WHERE_invite'				=> "Приглашает друга на сайт",
'WHERE_mail'				=> "Пишет e-mail пользователю",
'WHERE_usercp'				=> "В панели управления пользователя",
's_by'				=> "Сортировать по:",
'WHERE_msg'				=> "В системе личных сообщений",
's_sort_key_click'				=> "По последней активности",
's_sort_order_asc'				=> "По возрастанию",
's_sort_key_name'				=> "По имени пользователя",
's_sort_order_desc'				=> "По убыванию",
's_show_mem_guest'				=> "Показать только гостей",
's_show_mem_reg'				=> "Показать только зарегистрированных",
's_go'				=> "Обновить",
's_show_mem_all'				=> "Показать всех пользователей",
'member_name'				=> "Имя пользователя",
'time'				=> "Время",
'where'				=> "Где сейчас",
'users_online'				=> "Посетителей",
'page_title'				=> "Посетители",
'no_options_available'				=> "Нет доступных действий",
'not_online'				=> "Не на сайте",
'board_index'				=> "Смотрит главную страницу",
'WHERE_calendar'				=> "Смотрит календарь",
'WHERE_portal'				=> "Смотрит портал",
'WHERE_boardrules'				=> "Смотрит правила сайта",
'WHERE_sf'				=> "Смотрит форум:",
'WHERE_st'				=> "Смотрит тему:",
'WHERE_sr'				=> "Смотрит правила форума:",
'WHERE_login'				=> "Входит...",
'WHERE_postrep'				=> "Отвечает в теме:",
'WHERE_postnew'				=> "Создает тему в форуме:",
'WHERE_reg'				=> "Регистрируется....",
'WHERE_members'				=> "Смотрит список пользователей",
'WHERE_online'				=> "Смотрит список посетителей",
'WHERE_search'				=> "Использует поиск...",
'WHERE_help'				=> "Смотрит помощь",
'WHERE_print'				=> "Печатает тему",
'WHERE_forward'				=> "Отправляет ссылку на тему",
 ); 
