<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'portal_row_menu_settings'				=> "Edit Settings...",
'portal_row_menu_view_tags'				=> "View Exportable Tags...",
'main_title'				=> "Manage Portal Plug-ins",
'error_no_dir'				=> "The directory 'sources/portal_plugins' does not exist. Create it and try again.",
'error_no_key'				=> "There is no matching plug-in for the key used to find it.",
'error_no_settings'				=> "There are no settings for this plug-in",
'portal_main_key'				=> "Plug-in Title",
'portal_main_title'				=> "Registered Portal Plug-ins",
'portal_pop_name'				=> "Tag Name",
'portal_pop_tags'				=> "Exportable Tags:",
'portal_pop_desc'				=> "Tag Description",
 ); 
