<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.1.4 (31007) on Fri, 22 Apr 2011 00:40:56 +0000 by mikhail
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'but_forums'				=> "Форумы",
'print'				=> "Печать",
'email'				=> "Письмо",
'times_last'				=> "раз - последний",
'times_make'				=> "раз - добавить",
'but_active'				=> "Активные темы",
'recent_topics'				=> "Популярные темы",
'online_title'				=> "Сейчас на сайте",
'links_title'				=> "Навигация",
'online_breakdown'				=> "<strong>%s</strong> пользователей на сайте:",
'online_split'				=> "%s пользователей, %s гостей и %s анонимных пользователей",
'recent_read'				=> "Читали",
'poll_title'				=> "Опрос",
'recent_comments'				=> "Комментариев",
'article_comment'				=> "комментарий",
'discuss_title'				=> "Последние обсуждения",
'aff_title'				=> "Рекомендованные сайты",
'portal_by'				=> "от",
'read'				=> "Прочитано",
'comments_suffix'				=> "комментариев",
 ); 
